<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DoiNam2022</name>
   <tag></tag>
   <elementGuidId>7f30d70e-340f-40d9-b6ac-b9b19d0ff5a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='attendance_detail']/section[2]/section[1]/section[4]/section[1]/div[1]/section[1]/div[1]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
