<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID_employ</name>
   <tag></tag>
   <elementGuidId>5d0472cc-6723-4fa4-8a62-b276801fe0e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space()='${employ_id}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//p[normalize-space()='${employ_id}']</value>
      <webElementGuid>a6e1c1b5-ab0b-4fd1-be09-6ebcd030ce8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
