<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose_day93</name>
   <tag></tag>
   <elementGuidId>fe63783f-2e68-49f5-87a8-0b24436c8d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='attendance_detail']/section[1]/div[1]/section[1]/section[2]/section[1]/div[1]/section[2]/table[1]/tr[2]/td[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
