<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Day2</name>
   <tag></tag>
   <elementGuidId>4fffa384-31e9-4e55-9474-f02151d36c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='attendance_detail']/section[2]/section[1]/section[4]/section[1]/div[1]/section[2]/table[1]/tr[3]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
