<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Doithang1</name>
   <tag></tag>
   <elementGuidId>088a5fb9-dd7f-4bee-8791-0d6d85dc9fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/main[@id='attendance_detail']/section[2]/section[1]/section[4]/section[1]/div[1]/section[1]/div[2]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
